spring:
  datasource:
    url: jdbc:mysql://47.93.243.203:3306/mini_blogger?useSSL=false&nullNamePatternMatchesAll=true
    username: root
    password: hufeng
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    allow-request-override: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false



mybatis:
  mapper-locations:classpath:com/*/mapper/*Mapper.xml
