spring:
  datasource:
    url: jdbc:mysql://47.93.243.203:3306/mini_blogger?useSSL=false&nullNamePatternMatchesAll=true
    username: root
    password: hufeng
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations:classpath:com/*/mapper/*Mapper.xml

    #type: com.alibaba.druid.pool.DruidDataSource
    #initialSize: 1
    #minIdle: 3
    #maxActive: 20
    # 配置获取连接等待超时的时间
   #maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    #minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    #testWhileIdle: true
    #testOnBorrow: false
    #testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    #poolPreparedStatements: true
    #maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    # 下面为连接池的补充设置，应用到上面所有数据源中
